name: validator
on:
  pull_request:
    types: [ready_for_review]
jobs:
  validate_title:
    name: validate_title
    runs-on: ubuntu-latest
    steps:
      - name: validate title
        # shell: bash
        # run: ../validate.sh ${{ github.event.pull_request.title }}
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (!context.payload.pull_request.labels.find(e => e.name == 'WIP ğŸ–')) {
              return;
            }
            const REGEX = new RegExp(/^(feat|fix|docs|style|refactor|test|chore)\(.+\): .+/);
            if (!REGEX.test(context.payload.pull_request.title)) {
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'æ­£ã—ã„ã‚¿ã‚¤ãƒˆãƒ«ã«ã—ã¦ãã ã•ã„ã€‚\nã‚ˆã‚ã—ããŠé¡˜ã„ã—ã¾ã™ã€‚'
              })
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['please fix title!']
              })
            }